export const PermissionKeys = {
  agencyRead: 'agency.read',
  agencyUpdate: 'agency.update',
  agencyMemberRead: 'agency.member.read',
  agencyMemberCreate: 'agency.member.create',
  agencyMemberUpdate: 'agency.member.update',
  workspaceRead: 'workspace.read',
  workspaceCreate: 'workspace.create',
  workspaceUpdate: 'workspace.update',
  workspaceMemberRead: 'workspace.member.read',
  workspaceMemberCreate: 'workspace.member.create',
  workspaceMemberUpdate: 'workspace.member.update',
  usersView: 'users.view',
  usersManage: 'users.manage',
  departmentsView: 'departments.view',
  departmentsCreate: 'departments.create',
  departmentsUpdate: 'departments.update',
  departmentsManageMembers: 'departments.manage_members',
  rolesView: 'roles.view',
  rolesCreate: 'roles.create',
  rolesUpdate: 'roles.update',
  rolesManagePermissions: 'roles.manage_permissions',
  rolesAssign: 'roles.assign',
  statusesView: 'statuses.view',
  statusesCreate: 'statuses.create',
  statusesUpdate: 'statuses.update',
  statusesReorder: 'statuses.reorder',
  statusesManage: 'statuses.manage',
  tasksView: 'tasks.view',
  tasksCreate: 'tasks.create',
  tasksUpdate: 'tasks.update',
  tasksDelete: 'tasks.delete',
  tasksAssign: 'tasks.assign',
  tasksManage: 'tasks.manage',
  featureRead: 'feature.read',
  featureUpdate: 'feature.update',
  organizationRead: 'organization.read',
  organizationUpdate: 'organization.update',
  memberRead: 'member.read',
  memberCreate: 'member.create',
  memberUpdate: 'member.update',
  memberDelete: 'member.delete',
  projectRead: 'project.read',
  projectCreate: 'project.create',
  projectUpdate: 'project.update',
  projectDelete: 'project.delete',
  assetRead: 'asset.read',
  assetCreate: 'asset.create',
  assetDelete: 'asset.delete',
  assetDownload: 'asset.download',
} as const;

export const OWNER_ROLE = 'OWNER';
export const AGENCY_OWNER_ROLE = 'AGENCY_OWNER';
export const AGENCY_ADMIN_ROLES = ['AGENCY_OWNER', 'AGENCY_ADMIN'];
