const unitTestEnv: Record<string, string> = {
  NODE_ENV: 'test',
  APP_ENV: 'test',
  WEB_APP_URL: 'http://localhost:3000',
  API_PUBLIC_URL: 'http://localhost:7111/api/v1',
  CORS_ORIGINS: 'http://localhost:3000',
  CANONICAL_HOSTS: 'localhost,app.zeaplay.test',
  REQUEST_BODY_LIMIT: '1mb',
  DATABASE_URL: 'postgresql://zeaplay_unit:zeaplay_unit@127.0.0.1:15432/zeaplay_unit_test',
  DIRECT_DATABASE_URL: 'postgresql://zeaplay_unit:zeaplay_unit@127.0.0.1:15432/zeaplay_unit_test',
  REDIS_CACHE_URL: 'redis://127.0.0.1:16379',
  REDIS_QUEUE_URL: 'redis://127.0.0.1:16380',
  REDIS_REALTIME_URL: 'redis://127.0.0.1:16381',
  REDIS_RATE_LIMIT_URL: 'redis://127.0.0.1:16382',
  JWT_ACCESS_SECRET: 'unit-test-access-secret-at-least-32-characters',
  MINIO_ENDPOINT: '127.0.0.1',
  MINIO_PORT: '19000',
  MINIO_USE_SSL: 'false',
  MINIO_ACCESS_KEY: 'unit-test-minio-access-key',
  MINIO_SECRET_KEY: 'unit-test-minio-secret-key',
  MINIO_BUCKET: 'zeaplay-unit-test',
  EMAIL_PROVIDER: 'resend',
  EMAIL_FROM: 'no-reply@example.test',
  EMAIL_FROM_NAME: 'ZeaPlay Test',
  RESEND_API_KEY: 'unit-test-resend-api-key',
  OTP_PEPPER: 'unit-test-otp-pepper-at-least-32-characters',
  OTEL_EXPORTER_OTLP_ENDPOINT: 'http://127.0.0.1:4318',
};

Object.assign(process.env, unitTestEnv);
